### ISSUE TITLE
python run_image_captioning.py --dataset flickr

### ISSUE THREAD

**Issue by LISGCS** [junyangwang0410/Knight#2]
Hello, thank you for sharing code.

I have the following error when use Flickr30k on colab.

!python run_image_captioning.py --dataset flickr
FileNotFoundError: [Errno 2] No such file or directory: './feature/Flickr/nibers.npy'

**Comment by junyangwang0410** [comment]
Hello! Maybe you need to run _data_prepare_Flickr.py_ first to get the k-nearest-neighbor features. You need to modify the last line of _data_prepare_Flickr.py_ to save your **nibers.npy**. This is to extract the features in advance so that you can reduce the overhead in the training phase.
