### ISSUE TITLE
Question about the referenced sentences in reference_Flickr.json

### ISSUE THREAD

**Issue by blackantywj** [junyangwang0410/Knight#5]
Hello, Thank you for your open source~
The number of tests is 1014 in the reference_Flickr.json, but the number of image features is 1000. So i encounter the error of assertation about ref and gts. How can i solve it?😀

**Comment by UUUUUUccc** [comment]
Hi! I saw your comment about the mismatch between the number of tests in reference_Flickr.json (1014) and the image features (1000), which caused an assertion error between ref and gts. I’m facing the same issue—may I ask how you eventually solved it? Thanks in advance! 😊

**Comment by blackantywj** [comment]
Hello~ 

The Flickr 30K dataset has 1,014 validation images and 1,000 test images. Perhaps you also had some misunderstandings regarding the split name.
